In [1]:
import numpy as np 


In [6]:
#insert = insert new element into existing one 
#np.insert(array,index,value,axis = None)
arr = np.arange(1,6)
print(arr)
new_arr = np.insert(arr,2,78,axis = None)
print(new_arr)

[1 2 3 4 5]
[ 1  2 78  3  4  5]


In [17]:
multi = np.array([[1,2,3],[4,5,6]])
print(multi)

new_arr = np.insert(multi,1,[-1,-1,-1],axis = 0)
print(new_arr)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [-1 -1 -1]
 [ 4  5  6]]


In [21]:
#append 
arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)
print(np.append(arr1,arr2))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
#concatinate 
arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)
print(np.concatenate((arr1,arr2),axis = 0))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
#delete  
# - 1D array index = 0 
# - 2D array index = list at index 0  

arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)
print(np.delete(arr1,1,axis = 0))

[1 2 3 4 5]
[ 6  7  8  9 10]
[1 3 4 5]


In [33]:
#stacking 
#vstack 
#hstack 


arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))



[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [41]:
#splitting 

#vsplit()
#hsplit() 


arr1 = np.arange(1,5)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)

print(np.split(arr1,2))


[1 2 3 4]
[ 6  7  8  9 10]
[array([1, 2]), array([3, 4])]
