In [1]:
import numpy as np 

In [2]:
#checking the information 


In [11]:
#shape 
arr = np.eye(5)
print(arr)

print(arr.shape)
print(arr.size)
print(arr.dtype)


multi_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(multi_d_arr.ndim)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
25
float64
3


In [15]:
#changing the information 
arr = np.array([1.2,2.5,3.8])
print(arr)
print(arr.dtype)

new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[1.2 2.5 3.8]
float64
[1 2 3]
int64


In [23]:
# Maths functions on numpy arrays 

arr = np.arange(1,6)
print(arr)

print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)
print(arr ** 5)
print(arr % 5)

[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[   1   32  243 1024 3125]
[1 2 3 4 0]


In [25]:
#aggregation functions - gives summary 
arr = np.arange(10,51,10)
print(arr)

print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

[10 20 30 40 50]
10
50
150
30.0
14.142135623730951
200.0
