In [1]:
import numpy as np

In [2]:
#np.array()
lst = [1,3,4,5]
arr = np.array(lst)
arr

array([1, 3, 4, 5])

In [3]:
#np.zeros((shape)) - 
zeros_arr1 = np.zeros((2))
zeros_arr2 = np.zeros((2,3))
print(zeros_arr1)
zeros_arr2

[0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#np.ones((shape))
ones_arr1 = np.ones(5)
ones_arr2= np.ones((2,3))

print(ones_arr1)
ones_arr2


[1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
#np.full((shape),value)
filled_arr = np.full((3,3),14)
filled_arr

array([[14, 14, 14],
       [14, 14, 14],
       [14, 14, 14]])

In [13]:
#create range of list 
#np.arange(start,stop,step)
a1 = np.arange(2,10)
print(a1)
a2 = np.arange(1,10,2)
a2


[2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [16]:
#create identity matrix 
#np.eye(size)
identity_matrix = np.eye((5))
identity_matrix



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])