In [2]:
import numpy as np



In [9]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
#reshape = it will convert your array in specified shape (IF NUMBER OF ELEMENTS MATCH )
new_arr = arr.reshape(2,3)

new_arr


array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
#FLATTENING ARRAYS 
    # 1. ravel() -> view
    # 2. flatten() -> copy 

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ravel())
print(arr.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
